############## define directories that we work with #############
rawdatadir:
    "/home/ksr/Desktop/contact_localization/raw_msb/efri"
# "/Users/ChesterHuynh/sarmalab/contact_localization_proj/rawdata"
 # "/home/adam2392/hdd2/data/neuroimaging/raw"
# "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/raw/"

############# define FreeSurfer Subject Directory #############
fs_outputdatadir:
    "/home/ksr/Desktop/contact_localization/freesurfer_msb/efri"
# "/Users/ChesterHuynh/sarmalab/contact_localization_proj/fs_outputdata"
 # "/home/adam2392/hdd2/data/neuroimaging/freesurfer_output/"
# "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/freesurfer_output/"

############# define list of files to run this for #############
patients:
  [
     ## 'efri02',
     'efri06',
     #'efri07',
     #'efri09',
     ## 'efri10',
     ## 'efri13',
     ## 'efri14',
     ##'efri18',
     # 'efri20',
]
