############## define directories that we work with #############
# home directory that every dataset sits in -> fileutils sets the BIDS structure
bids_root:
#  "/home/ksr/Desktop/contact_localization/efri/"
#  "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/epilepsy/"
  "/home/data/epilepsy_bids/"
#  '/Users/adam2392/Downloads/neuroimg/'

derivatives_output_dir:
#    "/home/ksr/Desktop/contact_localization/efri/raw_msb/"
# "/Users/ChesterHuynh/sarmalab/contact_localization_proj/rawdata"
#  "/Users/adam2392/Downloads/neuroimg/derivatives/"
  "/home/data/derivatives/"

############# define list of files to run this for #############
patients:
  [
    'la02'
]

blender_path: # type in 'which blender' in command line
  "/usr/bin/blender/"
