# define directories that we work with
rawdatadir:
#  "~/sarmalab/contact_localization_proj/rawdata"
  "/home/adam2392/hdd/data/neuroimaging/raw"
#  "/home/adam2392/Documents/Dropbox/phd_research/data/neuroimaging_results/raw/"
# "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/raw/"
fs_outputdatadir:
#  "~/sarmalab/contact_localization_proj/fs_outputdata"
 "/home/adam2392/hdd/data/neuroimaging/freesurfer_output/"
#  "/home/adam2392/Documents/Dropbox/phd_research/data/neuroimaging_results/freesurfer_output/"
# "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/freesurfer_output/"
# define list of files to run this for
patients:
  [
#    'la02',
#    'la17',
#    'la23',
#    'la14',
#   'la03',
#   'la04',
#   'la05',
#   'la06',
#   'la07',
#    'la08',
#    'la09',
#    'la10',
#    'la11',
#    'la12',
#    'la13',
#    'la15',
#    'la16',
#    'la21',
#    'la22',
#    'la24',
#    'nl01',
#    'nl02',
#    'nl03',
#    'nl04',
#    'nl05',
#    'nl06',
#    'nl07',
#    'nl08',
#    'nl09',
#    'nl10',
#    'nl11',
#    'nl12',
#   'nl11',
#   'nl12',
#   'nl13',
#   'nl14',
#   'nl15',
#   'nl16',
#   'nl17',
#   'nl18',
#   'nl19',
#  'nl20',
#   'nl21',
#   'nl22',
#   'nl23',
#    'umf001',
#    'umf002',
#    'umf003',
#    'umf004',
#    'umf005',
    'tvb1',
    'tvb2',
    'tvb5',
    'tvb7',
    'tvb8',
    'tvb11',
    'tvb12',
    'tvb14',
    'tvb17',
    'tvb18',
    'tvb19',
    'tvb23'
]
