# define directories that we work with
rawdatadir:
#  "~/sarmalab/contact_localization_proj/rawdata"
# "/home/adam2392/hdd/data/neuroimaging/raw"
#  "/home/adam2392/Documents/Dropbox/phd_research/data/neuroimaging_results/raw/"
# "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/raw/"
    "/home/ksr/Desktop/contact_localization/raw" #2018/06/19
fs_outputdatadir:
#  "~/sarmalab/contact_localization_proj/fs_outputdata"
# "/home/adam2392/hdd/data/neuroimaging/freesurfer_output/"
#  "/home/adam2392/Documents/Dropbox/phd_research/data/neuroimaging_results/freesurfer_output/"
# "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/freesurfer_output/"
    "/home/ksr/Desktop/contact_localization/freesurfer_output"
# define list of files to run this for
patients:
  [
    #'efri06',
    ##'efri07',
    'efri10',
    #'efri12',
    #'efri13',
    #'efri15',
    'efri16'
    #'efri17',
    #'efri18',
    #'efri21'
  ]
