############## define directories that we work with #############
rawdatadir:
    "/home/ksr/Desktop/contact_localization/raw"
############# define FreeSurfer Subject Directory #############
fs_outputdatadir:
    "/home/ksr/Desktop/contact_localization/freesurfer_output"
############# define list of files to run this for #############
patients:
  [
#    'efri06',
#     'efri07',
#    'efri10',
#    'efri12',
#    'efri13',
#    'efri15',
#    'efri16'
#    'efri17',
#    'efri18',
#    'efri21'
#      'efri02',
#      'efri09',
#      'efri14',
#      'efri20'
  ]