services:
  - docker

language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - docker-ce

before_install:
  # make local input and output directories to attach to container
  - cd ..
  - mkdir -m 777 input output

  # useful log checks
  - readlink -f input
  - ls
  - pwd
  - uname -a
  - df -h
  - docker version

  # grab m2g's travis docker image, run it with local branch attached as a volume
  - docker pull neuroseek/seek:latest
  - docker images
#  - docker run -t -d --name travis -e MPLCONFIGDIR=/tmp/matplotlib -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/m2g -v $(readlink -f ../output):/output --entrypoint /bin/bash neurodata/m2g_travis:latest
  - docker ps

# command to install dependencies
install:
  # commands to get Miniconda3 setup
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test-env
  - conda init bash
  - source activate test-env
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda install numpy scipy matplotlib pytest scikit-learn pandas seaborn nibabel mne mne-bids snakemake ipykernel scikit-image flask
  # run conda /pip installation of packages
  - conda install -c anaconda natsort pytest black flake8 check-manifest pytest-cov pydocstyle
  - pip install codespell

# command to run tests
script:
  - pytest ./tests
  - make check
  - docker build --tag neuroseek .
  - docker run neuroseek