language: python
python:
  - "3.6"
# command to install dependencies
install:
  # commands to get Miniconda3 setup
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pytest scikit-learn pandas seaborn ipykernel
  - conda env create -f environment.yml
  - source activate test-env
  # run conda /pip installation of packages
  - conda install -c conda-forge mne
  - conda install -c anaconda natsort pylint flake8
  - conda install -c bioconda snakemake
# command to run tests
script:
  - pylint ./neuroimg/
  - pytest ./tests
