version: '3'
services:
  reconstruction:
    build: 
      context: . 
      dockerfile: ./neuroimg/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Data:/data
    environment:
      DISPLAY: 192.168.1.138:0.0
      bids_root: /data
      derivatives_output_dir: /data/derivatives
    command: tail -F anything

  # localization:
  #   build: 

  # visualizer:
  #   build: 