version: '3'
services:
  reconstruction:
    build: 
      context: . 
      dockerfile: seek/Dockerfile
    volumes:
      - ./Data:/data
    tty: true  # keep container running
    container_name: 'seek'

  localization:
    image: thebrainchain/bioimagesuite35:latest
    environment: 
      DISPLAY: 192.168.1.138:0.0
    volumes:
      - ./Data:/data
    depends_on:
      - "reconstruction"

    
  mesh_generator:
    container_name: mesh_generator
    image: neuroseek/3d_reconstruction:latest
    environment: 
      SUBJECT: la02
    volumes:
      - ./Data:/data

  mesh_visualizer:
    container_name: mesh_visualizer
    depends_on: 
      - mesh_generator
    image: neuroseek/recon_visualizer:latest
    environment: 
      SUBJECT: la02
    ports: 
      - 5000
    volumes:
      - ./Data:/data

