name: seek
channels:
- defaults
- conda-forge
- bioconda
dependencies:
- python>3.6
- pip>=20
- numpy>=1.14
- scipy>=0.18.1
- matplotlib
- snakemake
- dicom2nifti
- pip:
  - mne>=0.20
  - mne-bids>=0.4
  - nibabel>=2.2
  - pybv
  - nilearn
  - flake8
  - pytest
  - pytest-cov
  - pytest-sugar
  - check-manifest
  - pydocstyle
  - sphinx
  - pillow
  - numpydoc
  - sphinx_bootstrap_theme
  - sphinx_gallery
