############## define directories that we work with #############
# home directory that every dataset sits in -> fileutils sets the BIDS structure
bids_root:
#  "/home/ksr/Desktop/contact_localization/efri/"
#  "/Users/adam2392/Dropbox/efri/"
  "/home/adam2392/hdd2/epilepsy_bids/"
#  "/home/adam2392/hdd2/Dropbox/efri/"
#  '/Users/adam2392/Downloads/neuroimg/'

#derivatives_output_dir:
##    "/home/ksr/Desktop/contact_localization/efri/raw_msb/"
## "/Users/ChesterHuynh/sarmalab/contact_localization_proj/rawdata"
##  "/Users/adam2392/Downloads/neuroimg/derivatives/"
#  "/home/adam2392/hdd2/epilepsy_bids/derivatives/"

center_id:
#  "cleveland"
#  'umf',

session:
  "efri"

############# define list of files to run this for #############
patients:
  [
#   'la01',
   'la02', 'la03', 'la04', 'la05', 'la06', 'la07', 'la08', 'la09', 'la10', 'la11', 'la12',
   'la13', 'la15', 'la16', 'la17', 'la21', 'la22', 'la23', 'la24',
#   'la27', 'la28', 'la29', 'la31',

#   'efri02', 'efri06', 'efri07', 'efri09', 'efri10', 'efri12', 'efri13',
#   'efri14', 'efri15', 'efri16', 'efri17', 'efri18', 'efri20',
#   'efri21', 'efri25', 'efri26',
#    'umf001', 'umf002', 'umf003', 'umf005',
    #    'la01', 'la02', 'la03', 'la04', 'la05', 'la06', 'la07', 'la08', 'la09', 'la10', 'la11', 'la12',
    #    'la13', 'la15', 'la16', 'la17', 'la21', 'la22', 'la23', 'la24', 'la27', 'la28', 'la29', 'la31',
]